name: Get Citation Data

on: 
 page_build: 
 schedule:
  - cron:  '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Reqs
      run: |
        sudo apt-get install python3-setuptools
    - name: Run
      run: |
        pip3 install -r requirements.txt
        python3 main.py
        git add "results"
        git config --global user.email "andrewchoongwonlee@gmail.com"
        git config --global user.name "andrewcwlee-dev"
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -m "update google scholar $(date '+%Y-%m-%d %H:%M:%S')"
          git push
        fi